#!/usr/bin/python3
<!DOCTYPE html>
<html>
<head>
  <title>Header and Footer Page</title>
  <link rel="stylesheet" type="text/css" href="styles/3-common.css">
  <link rel="stylesheet" type="text/css" href="styles/3-header.css">
  <link rel="stylesheet" type="text/css" href="styles/3-footer.css">
  <link rel="shortcut icon" type="image/x-icon" href="images/icon.ico">
</head>
<body>
  <header>
    <div class="logo"></div>
  </header>
  <footer>Best School</footer>
</body>
</html>

